version: 2

models:
  - name: customer_orders
    columns:
      - name: order_id
        description: id of an order
        tests:
          - unique
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        description: id of an order
        tests:
          - unique
          - not_null
  - name: stg_customers
    columns:
      - name: customer_id
        description: id of a customer
        tests:
          - unique
          - not_null
  - name: stg_payments
    columns:
      - name: order_id
        description: id of an order
        tests:
          - unique
          - not_null
  - name: int_paid_orders
    columns:
      - name: order_id
        description: id of an order
        tests:
          - unique
          - not_null
  - name: fct_customer_orders
    columns:
      - name: order_id
        description: id of an order
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('customer_orders')
              field: order_id
    
    
    
    